### ISSUE TITLE
Create a counter/gauge metric that exposes scrape errors 

### ISSUE THREAD

**Issue by marcelcorso** [f1yegor/clickhouse_exporter#1]
Right now it's not easy to monitor if clickhouse_exporter can reach it's target. 

For example: To solve that problem Prometheus' `jmx_exporter` exposes a gauge:

```
# HELP jmx_scrape_error Non-zero if this scrape failed.
# TYPE jmx_scrape_error gauge
jmx_scrape_error 0.0
```

that goes to 1 when there is a problem scraping it's target. 

It would be great to have something like this for clickhouse_exporter.

**Comment by f1yegor** [comment]
Will look at this

**Comment by f1yegor** [comment]
it's already exposed `exporter_scrape_failures_total`
in grafana you can use `sum(exporter_scrape_failures_total) OR vector(0)`

PS. if you are using grafana you can also look at https://grafana.com/dashboards/882

**Comment by marcelcorso** [comment]
We are using the grafana dashboard 👍 . But because we have many clickhouse instances its getting a bit busy. But that's another problem :-) 

I saw the `exporter_scrape_failures_total` but I'm not sure how to alert on it. 

If the `rate(exporter_scrape_failures_total[1m]) > 0` sounds weird

**Comment by f1yegor** [comment]
Looks legit. If you have further question feel free to reopen an issue.
