### ISSUE TITLE
Exporting metrics with 'default' user disabled

### ISSUE THREAD

**Issue by samriang** [f1yegor/clickhouse_exporter#14]
Hi,

Is there any way to use this exporter with user credentials? I have ClickHouse instance without 'default' user and exporter can't receive any metric from 8123 port. 

Thank you.

**Comment by f1yegor** [comment]
can you test new build? implemented in https://github.com/f1yegor/clickhouse_exporter/pull/15

**Comment by f1yegor** [comment]
works after quick check. feel free to reopen if not
