### ISSUE TITLE
Dependencies packages are outdated

### ISSUE THREAD

**Issue by nelsonfassis** [f1yegor/clickhouse_exporter#19]
Can't install package as described on documentation.
After downloading and running make, those are the issues I get. Tried to download packages from prometheus-junkyard but still didn't work. 

```
clickhouse_exporter.go:16:2: cannot find package "github.com/prometheus/client_golang/prometheus" in any of:
	/usr/src/github.com/prometheus/client_golang/prometheus (from $GOROOT)
	/home/user/go/src/github.com/prometheus/client_golang/prometheus (from $GOPATH)
```

**Comment by nelsonfassis** [comment]
Was doing it wrong. 
go get -v github.com/f1yegor/clickhouse_exporter 
did the job. Miss understood how it was supposed to work.

**Comment by f1yegor** [comment]
:+1:
