### ISSUE TITLE
cant compile 

### ISSUE THREAD

**Issue by yctn** [f1yegor/clickhouse_exporter#31]
i ran a git clone https://github.com/f1yegor/clickhouse_exporter and then ran go get which gave me the following error:
`
 go get
# clickhouse_exporter
./clickhouse_exporter.go:32:25: cannot use e (type *exporter.Exporter) as type "clickhouse_exporter/vendor/github.com/prometheus/client_golang/prometheus".Collector in argument to "clickhouse_exporter/vendor/github.com/prometheus/client_golang/prometheus".MustRegister:
	*exporter.Exporter does not implement "clickhouse_exporter/vendor/github.com/prometheus/client_golang/prometheus".Collector (wrong type for Collect method)
		have Collect(chan<- "github.com/f1yegor/clickhouse_exporter/vendor/github.com/prometheus/client_golang/prometheus".Metric)
		want Collect(chan<- "clickhouse_exporter/vendor/github.com/prometheus/client_golang/prometheus".Metric)
`
Am i doing something wrong here

**Comment by dartvaper** [comment]
You should set GOROOT and gopath [look at this](https://stackoverflow.com/questions/7970390/what-should-be-the-values-of-gopath-and-goroot), for example.
Then just type `go get github.com/f1yegor/clickhouse_exporter/exporter`
and `cd ~/go/src/github.com/f1yegor/clickhouse_exporter`
After that we use Makefile:
`make init && make build` - is all you need :)

It helped me for the first time.
