### ISSUE TITLE
User level query stats

### ISSUE THREAD

**Issue by bobrik** [f1yegor/clickhouse_exporter#5]
Internally we have the following view:

```sql
CREATE MATERIALIZED VIEW IF NOT EXISTS system.clickhouse_query_stats_by_user ENGINE = SummingMergeTree(dummy_date, (type, user), 8192) POPULATE AS
SELECT
    toDate('1970-01-01') AS dummy_date,
    type,
    initial_user AS user,
    count(initial_user) AS count,
    sum(query_duration_ms) AS query_duration_ms,
    sum(read_rows) AS read_rows,
    sum(read_bytes) AS read_bytes
FROM system.query_log
GROUP BY
    type,
    user;
```

This can be used to retrieve query stats on user granularity to find offenders:

```
-- SELECT
--     type,
--     user,
--     sum(count) AS count,
--     sum(query_duration_ms) AS query_duration_ms,
--     sum(read_rows) AS read_rows,
--     sum(read_bytes) AS read_bytes
-- FROM system.clickhouse_query_stats_by_user
-- GROUP BY
--     type,
--     user
--
-- Example output:
--
-- ┌─type─┬─user─────┬─count─┬─query_duration_ms─┬───read_rows─┬───read_bytes─┐
-- │    2 │ mvavrusa │    78 │            104566 │ 75332316665 │ 422028872602 │
-- │    1 │ mvavrusa │    78 │                 0 │           0 │            0 │
-- │    3 │ mvavrusa │     8 │                 0 │           0 │            0 │
-- └──────┴──────────┴───────┴───────────────────┴─────────────┴──────────────┘
--
-- The column `type` has the following meaning:
--
-- 1 - successful start of query execution
-- 2 - successful end of query execution
-- 3 - exception before start of query execution
-- 4 - exception while query execution
```

We have a tool that scrapes ClickHouse instances and exports these metrics:

```
clickhouse_user_query_read_rows{cluster="http",type="end_success",user="mvavrusa"} 660593724120
```

This seems quite useful to have in prometheus exporter itself, but I'm not sure what's the best way to have it. Expect user to create the table for themselves? Install table automatically?

cc @vavrusa

**Comment by vavrusa** [comment]
I think this is generally useful, but zookeeper_exporter shouldn't create it automatically (it shouldn't even have write access). The view has schema compatible with query_log (apart from `count`), it's probably okay to just explain how to create a table in the README. If the program accepts an optional parameter with the name of this table, e.g. `-user_log_table=X`, it can learn what aggregations and dimensions are available in it (from `DESCRIBE TABLE`), so the table schema doesn't have to be exactly like mentioned here (if someone wants to monitor, say, queries by user-table, or quota_key).

**Comment by bobrik** [comment]
I thought about it for a bit and it seems more useful to enable ClickHouse support in `sql_exporter`:

* https://github.com/justwatchcom/sql_exporter

**Comment by bobrik** [comment]
We solved this with `sql_exporter` and it seems like a reasonable solution.
