### ISSUE TITLE
Consider moving Exporter type to the library package

### ISSUE THREAD

**Issue by AlekSi** [f1yegor/clickhouse_exporter#9]
That way it can be as a library by other processes.

**Comment by jpiper** [comment]
There's a `telemetry.address` flag in the command you can use to set the port number.

**Comment by AlekSi** [comment]
Yeah, I know, but that's not I want. I want to reuse exporter logic in my process written in Go, not to run a separate process. One example of having most of the logic in the library is https://github.com/prometheus/mysqld_exporter – note how `mysqld_exporter.go` only parses flags and starts collector, and collector itself is a separate library package.

**Comment by f1yegor** [comment]
Thanks @AlekSi will look this week
